### ISSUE TITLE
If a marketmaker is already running, it should use it

### ISSUE THREAD

**Issue by satindergrewal** [buildog/BarterDEX#27]
Currently if existing `marketmaker` process is already running, the app shows Login screen.

On submitting the password and trying login, the existing `marketmaker` process is killed.

this will allow debugging and also allows continuity of SWAP completions!
and on exit, there should be an option to stop marketmaker (using stop api), or to leave it running, with the leave it running being the defauly
otherwise you could lose money by not completing the atomic swap protocols for pending swaps

**Comment by buildog** [comment]
fixed by the use of passphrase api in https://github.com/buildog/BarterDEX/pull/28
