### ISSUE TITLE
Native Coin Wallets Not Working

### ISSUE THREAD

**Issue by SHossainKMD** [buildog/BarterDEX#29]
I have Bitcoin Core wallet running in native mode, it doesn't show up on the GUI. Only coins/assets that are activated in native mode using Agama wallet does show up on GUI.

**Comment by jl777** [comment]
if this is a real issue, it is not in the GUI. the problem is that the getcoins output is not having a non-zero height, please reproduce this with command line and when it is fixed, the gui will work

**Comment by jl777** [comment]
a workaround you can do is to just make a ~/.bitcoin and put the bitcoin.conf file there

**Comment by Nagaws** [comment]
Same issue I have encountered for KMD chain, where i used Different datadirectory on windows. Unable to fetch get coins
https://www.screencast.com/t/cs6LkXOHEkWS

**Comment by himu007** [comment]
Found the issue and fixed. I had ~/.bitcoin and bitcoin.conf file there but didn't have `server=1`. Adding that line made it work.

**Comment by buildog** [comment]
ok so closing it
