### ISSUE TITLE
GUI-errors

### ISSUE THREAD

**Issue by Rick-Bird** [buildog/BarterDEX#34]
Tested on Windows 7 64-Bit.
I was only able to login into BarterDEX after complete fresh installation and a reboot therefore with "test123" as a passphrase and an additional waiting time. No running coin wallets. While komodod.exe is running, no login is possible, without it, I get the error, that no coin wallet is running. Logout didn't work either.

As soon as komodod.exe is running (opened manually or through agama) will cause javascript errors after about 20-30 minutes. The time doesn't change a lot, if BarterDEX is started hours before komodod.exe, right before or even after. As soon as both are running, the errors occures about 20-30 minutes later. Capured them in screenshots:

http://www.bilder-hochladen.net/files/big/ht3p-4a-31d8.png
http://www.bilder-hochladen.net/files/big/ht3p-49-526c.png

The last one appears after some time as soon, as the last one is closed, even after closing the BarterDEX-app. Only after BarterDEX is completely closed through the task manager, the prompts stop.

**Comment by buildog** [comment]
It's because of multiple instance of the process running at the same time which is fixed by https://github.com/buildog/BarterDEX/issues/35
