### ISSUE TITLE
Login on Mac OSX

### ISSUE THREAD

**Issue by Kiruel** [buildog/BarterDEX#37]
Im on macOS 10.13, and i have a error when i login with anyphrase.

[https://imgur.com/a/lugvO](url)

The complete error:

> /Applications/barterDEX.app/Contents/Resources/app.asar.unpacked/node_modules/marketmaker/bin/darwin/x64/marketmaker ; exit;
➜  ~ /Applications/barterDEX.app/Contents/Resources/app.asar.unpacked/node_modules/marketmaker/bin/darwin/x64/marketmaker ; exit;
dyld: Library not loaded: /usr/local/opt/nanomsg/lib/libnanomsg.5.0.0.dylib
  Referenced from: /Applications/barterDEX.app/Contents/Resources/app.asar.unpacked/node_modules/marketmaker/bin/darwin/x64/marketmaker
  Reason: image not found
[1]    32281 abort
[Process completed]

**Comment by Kiruel** [comment]
The complete error:

> /Applications/barterDEX.app/Contents/Resources/app.asar.unpacked/node_modules/marketmaker/bin/darwin/x64/marketmaker ; exit;
➜  ~ /Applications/barterDEX.app/Contents/Resources/app.asar.unpacked/node_modules/marketmaker/bin/darwin/x64/marketmaker ; exit;
dyld: Library not loaded: /usr/local/opt/nanomsg/lib/libnanomsg.5.0.0.dylib
  Referenced from: /Applications/barterDEX.app/Contents/Resources/app.asar.unpacked/node_modules/marketmaker/bin/darwin/x64/marketmaker
  Reason: image not found
[1]    32281 abort
[Process completed]

**Comment by buildog** [comment]
@Kiruel did you tried with the latest release https://github.com/buildog/BarterDEX/releases/tag/v1.2 ?

**Comment by Kiruel** [comment]
Yes.

**Comment by buildog** [comment]
with the packaged app (dmg) or nodejs ? 
look like the output is from nodejs right ?

**Comment by buildog** [comment]
@Kiruel c'est assez étrange comme bug, tu as installé via le `dmg` en glissant déposant dans applications?

peux tu vérifier le contenu du packet? (click droit sur barterdex dans application, et suivre le chemin `Contents/Resources/app.asar.unpacked/node_modules/marketmaker/bin/darwin/x64/marketmaker` afin de vérifier si il existe bien)

**Comment by Kiruel** [comment]
@buildog Oui j'ai bien copier/coller le dmg.

Oui marketmaker ce trouve bien à cette endroit ainsi que libnanomsg.5.0.0.dylib et libnanomsg.5.1.0.dylib

J'ai toujours le probleme meme apres une reinstalle.

**Comment by buildog** [comment]
mhhh, peux tu essayer d'installer nanomsg, les instructions sont https://github.com/buildog/BarterDEX#1-install-dependencies

**Comment by Kiruel** [comment]
same problem

**Comment by buildog** [comment]
uploaded a fix on the dmg, could you please re-download, install and test ?

**Comment by buildog** [comment]
@Kiruel , we were able to reproduce and fixed in the latest release, so please feel free to close after you had a chance to test the fix
