### ISSUE TITLE
Problem to connect

### ISSUE THREAD

**Issue by nonene777** [buildog/BarterDEX#38]
![bug barterdex](https://user-images.githubusercontent.com/6106918/32237543-7ed5950e-be65-11e7-9f62-d62e4be79e29.PNG)
I'm on windows 10

**Comment by buildog** [comment]
Do you have a space in your username ?

**Comment by nonene777** [comment]
What do you mean?

**Comment by buildog** [comment]
Ton nom d'utilisateur sous windows contient un espace, c'est un bug que l'on vient de corriger.

Tu peux re-télécharger et ré isntaller https://github.com/buildog/BarterDEX/releases/download/v1.2/barterDEX.exe, ça devrait fonctionner :-)

Merci pour ton aide!
