### ISSUE TITLE
Suggestion: Show message on init when blockchain is loading

### ISSUE THREAD

**Issue by n41r0j** [buildog/BarterDEX#39]
Start BarterDEX, enter passphrase and click 'Login'. BarterDEX is now initialising. At the same time, Komodo is still loading its blockchain, which causes BarterDEX initialisation display to keep loading. 

Idea: Show message in initialisation screen that blockchain of a coin is still loading?

**Comment by buildog** [comment]
we only support electrum which is more user convenient
