### ISSUE TITLE
Marketmaker Unable to initialize on Windows OS

### ISSUE THREAD

**Issue by Nagaws** [buildog/BarterDEX#49]
After installing New Barterdex 1.3.1 version, Adding an passphrase  and clicking On login, unable to go through

-- Gui Just froze
-- Marketmaker seems to be not Initialized( checked In taskmanager)
-- Manually tried to start marketmaker from cmd Line It never start (gave an o/p  total redeemed and exited)

Environment  : --
Windows 2016
Windows 7

**Comment by buildog** [comment]
Fixed, was caused by the passphrase with white space
