### ISSUE TITLE
Mac : Values on Barter Dex are empty after clicking o the coin.

### ISSUE THREAD

**Issue by SRG1903** [buildog/BarterDEX#52]
* Login to Barter Dex
* Click on any coin that has amount/balance. I clicked on Komodo 
* There is no values like how many KMD are in wallet represented.
* The exchange coin values are not represented 
* Validation amount is empty.

Expected : Price of the coin to be exchanged, the amount/balance in your respective wallet , valuation amount should all be displayed.

https://www.screencast.com/t/Xn0CbjWiJ

**Comment by Kiruel** [comment]
It's because you have 0 komodo i guess.

**Comment by buildog** [comment]
it has been fixed after the listunspent implementation on master
