### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by togethercrypton** [buildog/BarterDEX#56]
I get a message "Thats bad" when I try to load the BarterDEX coins other than KMD which come standard in the install (running with AGAMA open on Windows 10)
As you responded to the passphrase - it worked very well when I deleted the spaces from the passphrase so can confirm on that bug.
When I added another coin type it repeatedly says "Thats bad" with the red screen of error - Then it re-loads the wallet.
No option to add coin running from Electrum rather than native, so that could be an issue.

**Comment by buildog** [comment]
fixed on master
