### ISSUE TITLE
Not Enough Funds

### ISSUE THREAD

**Issue by andreag100** [buildog/BarterDEX#60]
I sent 5.70 Kmd for testing, so far all looks good, except that when I try to create an order for 10 MNZ I get a red error message (Not Enough Funds)

The Kmd credit is shown in the wallet, the total for the order is a lot less than the credit, seems an error
![screen shot 2017-11-08 at 17 05 41](https://user-images.githubusercontent.com/1693169/32543183-7890566e-c4a7-11e7-88c6-1941c0203996.png)
![screen shot 2017-11-08 at 17 05 01](https://user-images.githubusercontent.com/1693169/32543197-838b74cc-c4a7-11e7-9955-6657a5d294a6.png)
![screen shot 2017-11-08 at 17 05 11](https://user-images.githubusercontent.com/1693169/32543204-8a43051e-c4a7-11e7-8863-248995d7effa.png)

**Comment by buildog** [comment]
fixed with latest version
