### ISSUE TITLE
1.3.5: couldnt connect to electrum server 

### ISSUE THREAD

**Issue by askz** [buildog/BarterDEX#65]
OS: Debian 9
BarterDEX: 1.3.5

When I add any kind of coin (mnz, kmd, etc) I have this error 
![couldn't connect !](https://user-images.githubusercontent.com/854038/32740734-283013a2-c8a4-11e7-8556-c6a6e405a667.png)

**Comment by buildog** [comment]
fixed with latest version

**Comment by askz** [comment]
can you release new version on github release page plz?

**Comment by quangmach** [comment]
I use macbook and have same issue with v1.3.5. Where can I find latest release?

**Comment by alex-tang** [comment]
buildog's repo is not the correct location to download the latest release of BarterDex.

Please refer to this repo and it's releases: https://github.com/KomodoPlatform/BarterDEX/releases
The darwin build is compatible with MacOS.
